local G = GLOBAL
---------------
local function CheckConfig(config)
  return G.GetModConfigData(config, "workshop-3597024951")
end
----------------
G.TUNING.JX_TUNING =
{
  ENABLE_JX_PIANO = true, --是否导入 miao/jx_piano.lua 文件，留作补丁
  
  ---
  --模组配置
  jx_recipes_sort = CheckConfig("jx_recipes_sort"),
  jx_island_switch = CheckConfig("jx_island_switch"),
  jx_basket_preserver = CheckConfig("jx_basket_preserver") or .85,
  jx_basket_containerslot = CheckConfig("jx_basket_containerslot") or 9,
  jx_hat_sunflower_waterproofer = CheckConfig("jx_hat_sunflower_waterproofer") or .3,
  jx_hat_sunflower_insulator = CheckConfig("jx_hat_sunflower_insulator") or 120,
  jx_hat_mexico_waterproofer = CheckConfig("jx_hat_mexico_waterproofer") or .3,
  jx_hat_mexico_insulator = CheckConfig("jx_hat_mexico_insulator") or 150,
  jx_hat_white_rose_waterproofer = CheckConfig("jx_hat_white_rose_waterproofer") or .3,
  jx_hat_white_rose_insulator = CheckConfig("jx_hat_white_rose_insulator") or 60,
  jx_hat_white_rose_armorabsorb = CheckConfig("jx_hat_white_rose_armorabsorb") or .8,
  jx_hat_white_rose_armoramount = CheckConfig("jx_hat_white_rose_armoramount") or 315,
  jx_hat_hepburn_waterproofer = CheckConfig("jx_hat_hepburn_waterproofer") or .3,
  jx_hat_hepburn_insulator = CheckConfig("jx_hat_hepburn_insulator") or 60,
  jx_hat_reindeer_insulator = CheckConfig("jx_hat_reindeer_insulator") or 120,
  jx_pack_preserver = CheckConfig("jx_pack_preserver") or .2,
  jx_backpack_containerslot = CheckConfig("jx_backpack_containerslot") or 12,
  jx_backpack_insulator = CheckConfig("jx_backpack_insulator") or 30,
  jx_backpack_2_containerslot = CheckConfig("jx_backpack_2_containerslot") or 12,
  jx_backpack_2_insulator = CheckConfig("jx_backpack_2_insulator") or 30,
  jx_backpack_3_containerslot = CheckConfig("jx_backpack_3_containerslot") or 8,
  jx_backpack_3_insulator = CheckConfig("jx_backpack_3_insulator") or 30,
  jx_backpack_3_stacksize = CheckConfig("jx_backpack_3_stacksize"),
  jx_backpack_4_containerslot = CheckConfig("jx_backpack_4_containerslot") or 8,
  jx_backpack_4_insulator = CheckConfig("jx_backpack_4_insulator") or 30,
  jx_backpack_4_preserver = CheckConfig("jx_backpack_4_preserver"),
  jx_backpack_5_containerslot = CheckConfig("jx_backpack_5_containerslot") or 8,
  jx_portabletent_uses = CheckConfig("jx_portabletent_uses") or 20,
  jx_portable_cook_pot_recipes = CheckConfig("jx_portable_cook_pot_recipes"),
  jx_portable_cook_pot_2_recipes = CheckConfig("jx_portable_cook_pot_2_recipes"),
  jx_tv_lightenable = CheckConfig("jx_tv_lightenable"),
  jx_tv_lightradius = CheckConfig("jx_tv_lightradius") or 5,
  jx_phonograph_hauntrez = CheckConfig("jx_phonograph_hauntrez"),
  jx_phonograph_hauntrez_num = CheckConfig("jx_phonograph_hauntrez_num") or 3,
  jx_fan_cooling_efficiency = CheckConfig("jx_fan_cooling_efficiency") or 1,
  jx_tapeplayer_tend = CheckConfig("jx_tapeplayer_tend"),
  jx_icebox_containerslot = CheckConfig("jx_icebox_containerslot") or 16,
  jx_icebox_recipe = CheckConfig("jx_icebox_recipe"),
  jx_icebox_reverse = CheckConfig("jx_icebox_reverse"),
  --jx_icebox_2_preserver = CheckConfig("jx_icebox_2_preserver") or .3,
  jx_icebox_2_recipe = CheckConfig("jx_icebox_2_recipe"),
  jx_icebox_2_reverse = CheckConfig("jx_icebox_2_reverse"),
  jx_icebox_big_reverse = CheckConfig("jx_icebox_big_reverse"),
  jx_icemaker_worktime = CheckConfig("jx_icemaker_worktime") or 5,
  jx_icemaker_recipe = CheckConfig("jx_icemaker_recipe"),
  jx_cookpot_cooktimemult = CheckConfig("jx_cookpot_cooktimemult") or .85,
  jx_cookpot_spoil = CheckConfig("jx_cookpot_spoil"),
  jx_cookpot_2_cooktimemult = CheckConfig("jx_cookpot_2_cooktimemult") or .8,
  jx_cookpot_2_spoil = CheckConfig("jx_cookpot_2_spoil"),
  jx_sewingmachine_finiteuses = CheckConfig("jx_sewingmachine_finiteuses") or 60,
  jx_sewingmachine_silk = CheckConfig("jx_sewingmachine_silk"),
  jx_disassembler_finiteuses = CheckConfig("jx_disassembler_finiteuses") or 5,
  jx_disassembler_worktime = CheckConfig("jx_disassembler_worktime") or 5,
  jx_canner_worktime = CheckConfig("jx_canner_worktime") or 4,
  jx_chest_containerslot = CheckConfig("jx_chest_containerslot") or 12,
  jx_chest_recipe = CheckConfig("jx_chest_recipe"),
  jx_chest_2_containerslot = CheckConfig("jx_chest_2_containerslot") or 12,
  jx_chest_2_recipe = CheckConfig("jx_chest_2_recipe"),
  jx_dress_form_containerslot = CheckConfig("jx_dress_form_containerslot") or 9,
  jx_fish_tank_sanityaura = CheckConfig("jx_fish_tank_sanityaura"),
  jx_fish_tank_aurasize = CheckConfig("jx_fish_tank_aurasize") or 15,
  jx_tent_uses = CheckConfig("jx_tent_uses"),
  jx_bathtub_efficiency = CheckConfig("jx_bathtub_efficiency") or 5,
  jx_bathtub_moisture = CheckConfig("jx_bathtub_moisture") or 0,
  jx_bathtub_finiteuses = CheckConfig("jx_bathtub_finiteuses") or 50,
  jx_bathtub_cutstone = CheckConfig("jx_bathtub_cutstone"),
  jx_piano_volume1 = CheckConfig("jx_piano_volume1") or 1,
  jx_piano_volume2 = CheckConfig("jx_piano_volume2") or .4,
  jx_flashlight_fastspeed = CheckConfig("jx_flashlight_fastspeed"),
  jx_lantern_fuel = CheckConfig("jx_lantern_fuel") or 3.75,
  jx_lantern_2_fuel = CheckConfig("jx_lantern_2_fuel") or 3.75,
  jx_lantern_3_fuel = CheckConfig("jx_lantern_3_fuel") or 3.75,
  jx_lantern_3_cd = CheckConfig("jx_lantern_3_cd") or 10,
  jx_holy_sword_weapondamage = CheckConfig("jx_holy_sword_weapondamage") or 42,
  jx_holy_sword_planardamage = CheckConfig("jx_holy_sword_planardamage") or 30,
  jx_holy_sword_finiteuses = CheckConfig("jx_holy_sword_finiteuses") or 200,
  jx_holy_sword_cd = CheckConfig("jx_holy_sword_cd") or 5,
  jx_holy_sword_ui = CheckConfig("jx_holy_sword_ui"),
  jx_holy_sword_volume = CheckConfig("jx_holy_sword_volume") or 1,
  jx_hat_sigurd_armorabsorb = CheckConfig("jx_hat_sigurd_armorabsorb") or .95,
  jx_hat_sigurd_planardefense = CheckConfig("jx_hat_sigurd_planardefense") or 5,
  jx_hat_sigurd_armoramount = CheckConfig("jx_hat_sigurd_armoramount") or 1050,
  jx_hat_sigurd_waterproofer = CheckConfig("jx_hat_sigurd_waterproofer") or .2,
  jx_cellar_maxsaltrock = CheckConfig("jx_cellar_maxsaltrock") or 35,
  jx_honey_box_preserver = CheckConfig("jx_honey_box_preserver") or .2,
  jx_fireplug_scale1 = CheckConfig("jx_fireplug_scale1") or .34,
  jx_war_hoe_finiteuses = CheckConfig("jx_war_hoe_finiteuses") or 300,
  jx_war_hoe_planardamage = CheckConfig("jx_war_hoe_planardamage") or 21,
  jx_pan_aoe = CheckConfig("jx_pan_aoe") or .2,
  jx_pan_eternity = CheckConfig("jx_pan_eternity"),
  jx_hat_iron_pan_armoramount = CheckConfig("jx_hat_iron_pan_armoramount") or 315,
  jx_hat_iron_pan_armorabsorb = CheckConfig("jx_hat_iron_pan_armorabsorb") or .8,
  jx_hat_iron_pan_waterproofer = CheckConfig("jx_hat_iron_pan_waterproofer") or .5,
  jx_weapon_finiteuses = CheckConfig("jx_weapon_finiteuses") or 275,
  jx_weapon_damage = CheckConfig("jx_weapon_damage") or 50,
  jx_table_9_wash = CheckConfig("jx_table_9_wash"),
  jx_car_damagemult = CheckConfig("jx_car_damagemult") or 1,
  jx_car_health = CheckConfig("jx_car_health") or 4000,
  jx_wagpunkbitskit_repair = CheckConfig("jx_wagpunkbitskit_repair") or 1000,
  jx_gears_repair = CheckConfig("jx_gears_repair") or 400,
  jx_car_recipe = CheckConfig("jx_car_recipe"),
  jx_car_drivenoise = CheckConfig("jx_car_drivenoise") or 1,
  jx_car_disable = CheckConfig("jx_car_disable"),
  jx_parts_engine = CheckConfig("jx_parts_engine") or 20,
  
  ----------
  JX_FLASHLIGHT_LIGHTNUM = 14,
}