Assets = 
{
  Asset("ATLAS", "images/inventoryimages/jx_inventoryimages1.xml"),
  Asset("IMAGE", "images/inventoryimages/jx_inventoryimages1.tex"),
  
  Asset("ATLAS", "images/jx_wardrobe_container.xml"),
  Asset("IMAGE", "images/jx_wardrobe_container.tex"),
  Asset("ATLAS", "images/jx_tab.xml"),
  Asset("IMAGE", "images/jx_tab.tex"),
  Asset("ATLAS", "images/jx_car_tab.xml"),
  Asset("IMAGE", "images/jx_car_tab.tex"),
  
  Asset("ATLAS", "images/jx_slots/jx_car_slot.xml"),
  Asset("IMAGE", "images/jx_slots/jx_car_slot.tex"),
  Asset("ATLAS", "images/jx_slots/jx_rocks_slot.xml"),
  Asset("IMAGE", "images/jx_slots/jx_rocks_slot.tex"),
  Asset("ATLAS", "images/jx_slots/jx_meat_dried_slot.xml"),
  Asset("IMAGE", "images/jx_slots/jx_meat_dried_slot.tex"),
  Asset("ATLAS", "images/jx_slots/jx_eyebone_slot.xml"),
  Asset("IMAGE", "images/jx_slots/jx_eyebone_slot.tex"),
  
  Asset("ATLAS", "images/jx_car_hud/whistle.xml"),
  Asset("IMAGE", "images/jx_car_hud/whistle.tex"),
  Asset("ATLAS", "images/jx_car_hud/music.xml"),
  Asset("IMAGE", "images/jx_car_hud/music.tex"),
  Asset("ATLAS", "images/jx_car_hud/pause.xml"),
  Asset("IMAGE", "images/jx_car_hud/pause.tex"),
  Asset("ATLAS", "images/jx_car_hud/Jingxi_Jazz.xml"),
  Asset("IMAGE", "images/jx_car_hud/Jingxi_Jazz.tex"),
  Asset("ATLAS", "images/jx_car_hud/Wilsons_Holiday.xml"),
  Asset("IMAGE", "images/jx_car_hud/Wilsons_Holiday.tex"),
  Asset("ATLAS", "images/jx_car_hud/XunCat_Pop.xml"),
  Asset("IMAGE", "images/jx_car_hud/XunCat_Pop.tex"),
  
  Asset("ATLAS", "images/jx_piano_hud/jx_piano_panel_1.xml"),
  Asset("IMAGE", "images/jx_piano_hud/jx_piano_panel_1.tex"),
  Asset("ATLAS", "images/jx_piano_hud/jx_piano_panel_2.xml"),
  Asset("IMAGE", "images/jx_piano_hud/jx_piano_panel_2.tex"),
  Asset("ATLAS", "images/jx_piano_hud/jx_piano_key.xml"),
  Asset("IMAGE", "images/jx_piano_hud/jx_piano_key.tex"),
  Asset("ATLAS", "images/jx_piano_hud/jx_piano_tutorial_board.xml"),
  Asset("IMAGE", "images/jx_piano_hud/jx_piano_tutorial_board.tex"),
  
  Asset("ATLAS", "images/jx_holy_sword_hud/jx_holy_sword_button_off.xml"),
  Asset("IMAGE", "images/jx_holy_sword_hud/jx_holy_sword_button_off.tex"),
  Asset("ATLAS", "images/jx_holy_sword_hud/jx_holy_sword_button_on.xml"),
  Asset("IMAGE", "images/jx_holy_sword_hud/jx_holy_sword_button_on.tex"),
  
  Asset("ATLAS", "images/jx_trash_can_hud/jx_trash_can_button.xml"),
  Asset("IMAGE", "images/jx_trash_can_hud/jx_trash_can_button.tex"),
  
  Asset("ANIM", "anim/ui_jx_basket_3x3.zip"),
  Asset("ANIM", "anim/ui_jx_basket_2x2.zip"),
  Asset("ANIM", "anim/ui_jx_car_5x5.zip"),
  Asset("ANIM", "anim/ui_jx_rug_bag_5x5.zip"),
  Asset("ANIM", "anim/ui_jx_icebox_2_3x3.zip"),
  Asset("ANIM", "anim/ui_jx_cellar_5x5.zip"),
  Asset("ANIM", "anim/ui_jx_hay_cart_5x5.zip"),
  Asset("ANIM", "anim/ui_jx_hay_cart_4x4.zip"),
  Asset("ANIM", "anim/ui_jx_rock_bin_5x5.zip"),
  Asset("ANIM", "anim/ui_jx_storage_basket_4x4.zip"),
  Asset("ANIM", "anim/ui_jx_icebox_big_5x4.zip"),
  
  Asset("ANIM", "anim/wilsonjxdrive.zip"),
  Asset("ANIM", "anim/wilsonjxflashlight.zip"),
  Asset("ANIM", "anim/wilsonjxhangingbed.zip"),
  Asset("ANIM", "anim/wilsonjxdrink.zip"),
  
  Asset("ANIM", "anim/jx_car_hud.zip"),
  Asset("ANIM", "anim/jx_car_mark.zip"),
  Asset("ANIM", "anim/jx_car_record.zip"),
  
  Asset("SOUND", "sound/jx_sound_1.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_sound_1.fev"),
  Asset("SOUND", "sound/jx_sound_2.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_sound_2.fev"),
  Asset("SOUND", "sound/jx_sound_3.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_sound_3.fev"),
  Asset("SOUND", "sound/jx_sound_4.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_sound_4.fev"),
  Asset("SOUND", "sound/jx_sound_5.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_sound_5.fev"),
  Asset("SOUND", "sound/jx_sound_6.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_sound_6.fev"),
  Asset("SOUND", "sound/jx_sound_7.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_sound_7.fev"),
  Asset("SOUND", "sound/jx_sound_8.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_sound_8.fev"),
  Asset("SOUND", "sound/jx_sound_9.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_sound_9.fev"),
  Asset("SOUND", "sound/fire_machete.fsb"),
  Asset("SOUNDPACKAGE", "sound/fire_machete.fev"),
  Asset("SOUND", "sound/jx_car_explosion.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_car_explosion.fev"),
  Asset("SOUND", "sound/jx_car_music.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_car_music.fev"),
  Asset("SOUND", "sound/pianofx.fsb"),
  Asset("SOUNDPACKAGE", "sound/pianofx.fev"),
  Asset("SOUND", "sound/jx_flowing_water.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_flowing_water.fev"),
  Asset("SOUND", "sound/jx_piano.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_piano.fev"),
  Asset("SOUND", "sound/jx_holy_sword.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_holy_sword.fev"),
  Asset("SOUND", "sound/jx_canner.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_canner.fev"),
  Asset("SOUND", "sound/jx_charcoal_stove.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_charcoal_stove.fev"),
  Asset("SOUND", "sound/jx_icebox_big.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_icebox_big.fev"),
  Asset("SOUND", "sound/jx_backpack_5.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_backpack_5.fev"),
  Asset("SOUND", "sound/jx_bankatm_open.fsb"),
  Asset("SOUNDPACKAGE", "sound/jx_bankatm_open.fev"),
}

local InventoryItem_LIST = {
    "jx_icebox",
    "jx_icebox_2",
    "jx_icebox_big",
    "jx_cookpot",
    "jx_cookpot_2",
    "jx_chest",
    "jx_chest_2",
    "jx_tent",
    "jx_fish_tank",
    "jx_phonograph",
    "jx_tapeplayer",
    "jx_tv",
    "jx_mushroom_light",
    "jx_mushroom_light_2",
    "jx_lamp",
    "jx_lamp_2",
    "jx_furnace",
    "jx_wardrobe",
    "jx_sewingmachine",
    "jx_oven",
    "jx_backpack",
    "jx_backpack_2",
    "jx_backpack_3",
    "jx_backpack_4",
    "jx_backpack_5",
    "jx_pack",
    "jx_mailbox",
    "jx_bathtub",
    "jx_fan",
    "jx_well",
    "jx_washer",
    "jx_toilet_suction",
    "jx_wateringcan",
    "jx_toaster",
    "jx_toaster1",
    "jx_toaster2",
    "jx_toaster3",
    "jx_toaster4",
    "jx_toaster5",
    "jx_basket",
    "jx_bookcase",
    "jx_icemaker",
    "jx_lantern",
    "jx_lantern_2",
    "jx_lantern_3",
    "jx_car",
    "jx_gasoline",
    "jx_car_key",
    "jx_rug_bag",
    "jx_piano",
    "jx_fountain",
    "jx_fireplug",
    "jx_dress_form_m",
    "jx_dress_form_w",
    "jx_saxophone",
    "jx_cello",
    "jx_harp",
    "jx_cellar",
    "jx_hay_cart",
    "jx_handcart",
    "jx_pickling_barrel",
    "jx_holy_sword",
    "jx_wood_bin",
    "jx_rock_bin",
    "jx_wiki_book",
    "jx_war_hoe",
    "jx_mantel_clock",
    "jx_flashlight",
    "jx_battery1",
    "jx_battery2",
    "jx_portabletent",
    "jx_portabletent_item",
    "jx_hanging_bed",
    "jx_storage_basket",
    "jx_honey_box",
    "jx_disassembler",
    "jx_cabinet",
    "jx_canner",
    "jx_can0",
    "jx_can1",
    "jx_can2",
    "jx_charcoal_stove",
    "jx_chester_house",
    "jx_glommer_house",
    "jx_cat_tree",
    "jx_colchicum",
    "jx_portable_cook_pot",
    "jx_portable_cook_pot_item",
    "jx_portable_cook_pot_2",
    "jx_portable_cook_pot_2_item",
    "jx_trash_can",
    "jx_vending_machine",
    "jx_drink_cola",
    "jx_drink_tea",
    "jx_drink_coffee",
    "jx_bankatm",
    "jx_catcoin",
    "jx_farm_tools_container",
    "jx_frog_raincoat",
    
    "chesspiece_jx",
    "chesspiece_jx_moonglass",
    "chesspiece_jx_stone",
    
    "jx_sofa_1",
    "jx_sofa_2",
    "jx_sofa_3",
    
    "jx_chair_1",
    "jx_chair_2",
    "jx_chair_3",
    "jx_chair_4",
    
    "jx_table",
    "jx_table_2",
    "jx_table_3",
    "jx_table_4",
    "jx_table_5",
    "jx_table_6",
    "jx_table_7",
    "jx_table_8",
    "jx_table_9",
    
    "jx_potted",
    "jx_potted_sunflower",
    "jx_potted_cherry",
    "jx_potted_rose",
    "jx_potted_cactus",
    "jx_potted_anthurium",
    "jx_potted_narcissus",
    "jx_potted_snakeplant",
    "jx_red_rose_potted",
    "jx_green_palm",
    "jx_potted_gardenia",
    "jx_potted_monstera",
    "jx_rose_big_potted",
    "jx_chlorophytum_comosum_potted",
    "jx_perfume_potted",
    "jx_princess_potted",
    "jx_potted_berry",
    "jx_potted_mexico",
    "jx_xuncat",--喔喔！
    
    "jx_rug_oval",
    "jx_rug_oval_item",
    "jx_rug_forest",
    "jx_rug_forest_item",
    "jx_rug_triangle",
    "jx_rug_triangle_item",
    "jx_rug_aubusson",
    "jx_rug_aubusson_item",
    "jx_rug_tradition",
    "jx_rug_tradition_item",
    "jx_rug_savannah",
    "jx_rug_savannah_item",
    "jx_rug_platoni",
    "jx_rug_platoni_item",
    
    "turf_granite",
    "turf_reddish_brown",
    "turf_corridor",
    "turf_bath",
    "turf_jx_wood",
    "turf_jx_courtyard",
    
    "jx_hat_iron_pan",
    "jx_hat_white_rose",
    "jx_hat_sunflower",
    "jx_hat_sigurd",
    "jx_hat_hepburn",
    "jx_hat_mexico",
    "jx_hat_reindeer",
    "jx_hat_noodles",
    "jx_hat_motorcycle",
    
    "jx_pan",
    "jx_baguette",
    "jx_kebab",
    "jx_weapon_1",
    "jx_weapon_2",
    "jx_weapon_3",
    "jx_weapon_4",
    "jx_weapon_5",
    
    "wall_jx_stone",
    "wall_jx_stone_item",
    "wall_jx_stone_2",
    "wall_jx_stone_2_item",
    "wall_jx_stone_3",
    "wall_jx_stone_3_item",
    "wall_jx_straw_1",
    "wall_jx_straw_1_item",
    "jx_fence",
    "jx_fence_item",
    "jx_fence_2",
    "jx_fence_2_item",
    
    "jx_parts_light",
    "jx_parts_colour",
    "jx_parts_engine",
    "jx_parts_music",
    "jx_parts_wheel",
    "jx_parts_camera_1",
    "jx_parts_camera_2",
}

for _, v in ipairs(InventoryItem_LIST) do
  RegisterInventoryItemAtlas("images/inventoryimages/jx_inventoryimages1.xml", v..".tex")
end

AddMinimapAtlas("images/inventoryimages/jx_inventoryimages1.xml")

----------------------------------------------------------------------------
--小木牌
local function MiniSignPostinit(inst)
	if inst.components.drawable ~= nil then
		local oldondrawnfn = inst.components.drawable.ondrawnfn or nil
		inst.components.drawable.ondrawnfn = function(inst, image, src, atlas, bgimage, bgatlas, ...)
			if oldondrawnfn ~= nil then
				oldondrawnfn(inst, image, src, atlas, bgimage, bgatlas, ...)
			end
      
      local atlas_path = "images/inventoryimages/jx_inventoryimages1.xml"
			if image ~= nil and table.contains(InventoryItem_LIST, image) then
        inst.AnimState:OverrideSymbol("SWAP_SIGN", atlas_path, image..".tex")
			end
      if bgimage ~= nil and table.contains(InventoryItem_LIST, bgimage) then
        inst.AnimState:OverrideSymbol("SWAP_SIGN_BG", atlas_path, bgimage..".tex")
      end
		end
	end
end

AddPrefabPostInit("minisign", MiniSignPostinit)
AddPrefabPostInit("minisign_drawn", MiniSignPostinit)
AddPrefabPostInit("decor_pictureframe", MiniSignPostinit)