local KodiTuning = {}
local _GetModConfigData = nil
function KodiTuning.SetConfigGetter(fn)
    _GetModConfigData = fn
end
local function GetConfig(name, default)
    if _GetModConfigData then
        local value = _GetModConfigData(name)
        if value ~= nil then
            return value
        end
    end
    return default
end
function KodiTuning.Apply(TUNING)
    TUNING.KODI_MAX_HP = 150
    TUNING.KODI_MAX_SANITY = 125
    TUNING.KODI_MAX_HUNGER = 125
    TUNING.KODI_DAMAGEMULT = 0.95
    TUNING.KODI_SPEED = 1.10
    TUNING.KODI_HEALTH = TUNING.KODI_MAX_HP
    TUNING.KODI_HUNGER = TUNING.KODI_MAX_HUNGER
    TUNING.KODI_SANITY = TUNING.KODI_MAX_SANITY
    TUNING.KODI_DAMAGEBLOCK = 0.10
    TUNING.KODI_SPEEDTRANSFORM = 1.25
    TUNING.KODI_DAMAGETRANSFORM = 2.00
    TUNING.KODI_DEMONIC_MAX = 100
    TUNING.KODI_DEMONIC_FUEL_COUNT = GetConfig("demonicfuel_count", 6)
    TUNING.KODI_DEMONIC_FUEL_EFFICIENCY = 0.70
    TUNING.KODI_DEMONIC_PER_FUEL = (TUNING.KODI_DEMONIC_MAX * TUNING.KODI_DEMONIC_FUEL_EFFICIENCY) / TUNING.KODI_DEMONIC_FUEL_COUNT
    TUNING.KODI_TRANSFORM_DURATION = GetConfig("transform_duration", 70)
    TUNING.KODI_DEMONIC_DRAIN_RATE = TUNING.KODI_DEMONIC_MAX / TUNING.KODI_TRANSFORM_DURATION
    TUNING.KODI_KILL_ENERGY_BONUS = GetConfig("kill_energy_bonus", 5)
    TUNING.KODI_SHADOW_DASH_COST = GetConfig("shadow_dash_cost", 10)
    TUNING.KODI_LANGUAGE = GetConfig("kodilanguage", "ENGLISH")
    TUNING.KITSUNE_MASK_COOLDOWN = GetConfig("cooldown", 5)
    TUNING.KITSUNE_MASK_ATTACKNUM = GetConfig("attacknumber", 6)
    TUNING.KITSUNE_MASK_FREEZE = GetConfig("freeze", 0.20)
    TUNING.KITSUNE_MASK_DELTA_FEUL = TUNING.KITSUNE_MASK_ATTACKNUM * TUNING.TINY_FUEL
    TUNING.KITSUNE_MASK_MAX_FEUL = 4 * TUNING.LARGE_FUEL
    TUNING.KITSUNE_MASK_DAMAGE_FREEZE = GetConfig("damagefreeze", 50)
    TUNING.KITSUNE_MASK_FREEZE_TIME = GetConfig("freezetime", 2)
    TUNING.KODI_SHADOW_DASH_MIN_DISTANCE = 2
    TUNING.KODI_SHADOW_DASH_ENERGY_PER_TILE = 1.5
    TUNING.KODI_SHADOW_DASH_MIN_ENERGY = 5
    TUNING.KODI_SHADOW_DASH_ENERGY_RESERVE = 10
    TUNING.KODI_SHADOW_DASH_BASE_COOLDOWN = 1.0
    TUNING.KODI_SHADOW_DASH_MAX_RANGE = 36
    TUNING.KODI_SHADOW_DASH_PATH_DAMAGE = 20
    TUNING.KODI_SHADOW_DASH_PATH_WIDTH = 2
    TUNING.KODI_DOUBLE_TAP_WINDOW = 0.3
    TUNING.KODI_GAMEPAD_DASH_DISTANCE = 12
    TUNING.KODI_DEBUG_SKILLTREE = false
    TUNING.KODI_SHADOW_MINION_CORPSE_SEARCH_RADIUS = 6
    TUNING.KODI_SHADOW_MINION_FOLLOW_DISTANCE = 4
    TUNING.KODI_SHADOW_MINION_ATTACK_RANGE = 15
    TUNING.KODI_SHADOW_MINION_LIFETIME_MIN = 180
    TUNING.KODI_SHADOW_MINION_LIFETIME_MAX = 240
    TUNING.KODI_SHADOW_MINION_EXPLOSION_DAMAGE = 50
    TUNING.KODI_SHADOW_MINION_EXPLOSION_RADIUS = 5
    TUNING.KODI_SHADOW_MINION_COOLDOWN = 120
    TUNING.KODI_SHADOW_MINION_TELEPORT_DISTANCE = 40
    TUNING.KODI_SHADOW_MINION_STUCK_TIME = 5
    TUNING.KODI_SHADOW_MINION_STUCK_THRESHOLD = 2
    TUNING.KODI_SHADOW_SPIDERQUEEN_HEALTH = 1500
    TUNING.KODI_SHADOW_SPIDERQUEEN_DAMAGE = 60
    TUNING.KODI_SHADOW_SPIDERQUEEN_ATTACK_PERIOD = 3
    TUNING.KODI_SHADOW_SPIDERQUEEN_ATTACK_RANGE = 5
    TUNING.KODI_SHADOW_SPIDERQUEEN_WALKSPEED = 1.75
    TUNING.KODI_SHADOW_SPIDERQUEEN_MAX_BABIES = 6
    TUNING.KODI_SHADOW_SPIDERQUEEN_BABY_LIFETIME = 45
    TUNING.KODI_SHADOW_SPIDERQUEEN_BABY_SPAWN_PERIOD = 12
    TUNING.KODI_SHADOW_SPIDERQUEEN_BASE_LIFETIME = 300
    TUNING.KODI_NIGHT_HUNTER_LEAP_MULT_DAY = 1.1
    TUNING.KODI_NIGHT_HUNTER_LEAP_MULT_NIGHT = 2.5
    TUNING.KODI_NIGHT_HUNTER_LEAP_RANGE_DAY = 15
    TUNING.KODI_NIGHT_HUNTER_LEAP_RANGE_NIGHT = 20
    TUNING.KODI_NIGHT_HUNTER_CHASE_SPEED = 1.2
    TUNING.KODI_NIGHT_HUNTER_MARK_DURATION = 30
    TUNING.KODI_NIGHT_HUNTER_MAX_MARKS = 3
    TUNING.KODI_NIGHT_HUNTER_LINKED_DAMAGE = 0.5
    TUNING.KODI_NIGHT_HUNTER_LEAP_COOLDOWN = 30
    TUNING.KODI_NIGHT_HUNTER_VISION_ENERGY_DRAIN = 2
    TUNING.KODI_NIGHT_HUNTER_VISION_SANITY_DRAIN = 3
    TUNING.KODI_DAY_STALKER_POUNCE_MULT = 2.5
    TUNING.KODI_DAY_STALKER_SPEED_MULT = 0.5
    TUNING.KODI_DAY_STALKER_ALPHA = 0.4
    TUNING.KODI_DAY_STALKER_FADE_TIME = 3.0
    TUNING.KODI_DAY_STALKER_DETECTION_RANGE = 8
    TUNING.KODI_DAY_STALKER_DANGER_RANGE = 4
    TUNING.KODI_DAY_STALKER_LEAP_RANGE = 10
    TUNING.KODI_DAY_STALKER_LEAP_SPEED = 25
    TUNING.KODI_DAY_STALKER_LEAP_HEIGHT = 2
    TUNING.KODI_DAY_STALKER_HIDE_TIMEOUT = 20
    TUNING.KODI_DAPPERNESS_DAY_PENALTY = 5/60
    TUNING.KODI_DAPPERNESS_NIGHT_COMFORT = 6/60
    TUNING.KODI_DAPPERNESS_NIGHT_HUNTER = 15/60
    TUNING.KODI_SHADOW_ERUPTION_COOLDOWN = 20
    TUNING.KODI_SHADOW_CACHE_COOLDOWN = 10
    TUNING.KODI_SKILL_THRESHOLDS = {
        2,
        2,
        3,
        3,
        4,
        4,
        5,
        5,
        5,
        6,
        6,
        7,
        7,
        8,
        8,
        8,
    }
    TUNING.CURSEFOX = {
        LEAP_RANGE = 8,
        LEAP_COOLDOWN = 30,
        LEAP_DAMAGE = 100,
        LEAP_RADIUS = 3,
        LEAP_TENTACLES = 4,
    }
    TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.KODI = {"bedroll_fox_furry", "whiteamulet", "fox_wool"}
    TUNING.STARTING_ITEM_IMAGE_OVERRIDE["bedroll_fox_furry"] = {
        atlas = "images/inventoryimages/bedroll_fox_furry.xml",
        image = "bedroll_fox_furry.tex",
    }
    TUNING.STARTING_ITEM_IMAGE_OVERRIDE["whiteamulet"] = {
        atlas = "images/inventoryimages/whiteamulet.xml",
        image = "whiteamulet.tex",
    }
    TUNING.STARTING_ITEM_IMAGE_OVERRIDE["fox_wool"] = {
        atlas = "images/inventoryimages/fox_wool.xml",
        image = "fox_wool.tex",
    }
end
function KodiTuning.GetBadgePosition()
    return {
        x = GetConfig("badge_pos_x", -120),
        y = GetConfig("badge_pos_y", -40),
    }
end
function KodiTuning.GetTransformKey()
    return GetConfig("key_kodi", 120)
end
function KodiTuning.GetCooldownColor()
    return GetConfig("cooldownColor", 0.0)
end
return KodiTuning
