local ThePlayer = GLOBAL.ThePlayer
local TheInput = GLOBAL.TheInput
local SpawnPrefab = GLOBAL.SpawnPrefab

GLOBAL.setmetatable(env,{__index=function(t,k) return GLOBAL.rawget(GLOBAL,k) end})

----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----

STRINGS.UI.CRAFTING_FILTERS.GW_SHAOBING = "哨兵"

STRINGS.UI.CRAFTING_FILTERS.GW_HEIWU = "黑雾"

STRINGS.NAMES.GWEN_BOX = "格温的衣服匣"								----名字
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GWEN_BOX = "格温的衣服匣"			----检查台词

STRINGS.NAMES.GWEN_JIANDAO = "格温的剪刀"								----名字
STRINGS.RECIPE_DESC.GWEN_JIANDAO = "抬起头，仰起脸，剪刀也拿好了~"		----配方介绍
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GWEN_JIANDAO = "格温的剪刀"			----检查台词

STRINGS.NAMES.GW_MAOZI_ZHANDOU = "卫士之环"
STRINGS.RECIPE_DESC.GW_MAOZI_ZHANDOU = " 格温的卫士之环"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_MAOZI_ZHANDOU = "格温的卫士之环"

STRINGS.NAMES.GW_YIFU_ZHANDOU = "战斗华服"
STRINGS.RECIPE_DESC.GW_YIFU_ZHANDOU = " 格温的战斗华服"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_YIFU_ZHANDOU = "格温的战斗华服"

STRINGS.NAMES.GW_MAOZI_ZHANDOU2 = "天界之环"
STRINGS.RECIPE_DESC.GW_MAOZI_ZHANDOU2 = " 格温的天界之环"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_MAOZI_ZHANDOU2 = "格温的天界之环"

STRINGS.NAMES.GW_YIFU_ZHANDOU2 = "灵月华服"
STRINGS.RECIPE_DESC.GW_YIFU_ZHANDOU2 = " 格温的灵月华服"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_YIFU_ZHANDOU2 = "格温的灵月华服"

STRINGS.NAMES.GW_MAOZI_NVPU = "女仆发圈"
STRINGS.RECIPE_DESC.GW_MAOZI_NVPU = " 格温的女仆发圈"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_MAOZI_NVPU = "格温的女仆发圈"

STRINGS.NAMES.GW_YIFU_NVPU = "女仆围裙"
STRINGS.RECIPE_DESC.GW_YIFU_NVPU = " 格温的女仆围裙"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_YIFU_NVPU = "格温的女仆围裙"

STRINGS.NAMES.GW_MAOZI_DACHU = "厨师帽"
STRINGS.RECIPE_DESC.GW_MAOZI_DACHU = " 格温的厨师帽"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_MAOZI_DACHU = "格温的厨师帽"

STRINGS.NAMES.GW_YIFU_DACHU = "厨师围裙"
STRINGS.RECIPE_DESC.GW_YIFU_DACHU = " 格温的厨师围裙"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_YIFU_DACHU = "格温的厨师围裙"

STRINGS.NAMES.GW_MAOZI_YUANDING = "园丁帽"
STRINGS.RECIPE_DESC.GW_MAOZI_YUANDING = " 格温的园丁帽"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_MAOZI_YUANDING = "格温的园丁帽"

STRINGS.NAMES.GW_YIFU_YUANDING = "园丁围裙"
STRINGS.RECIPE_DESC.GW_YIFU_YUANDING = " 格温的园丁围裙"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_YIFU_YUANDING = "格温的园丁围裙"

STRINGS.NAMES.GW_MAOZI_SHENGDAN = "圣诞帽"
STRINGS.RECIPE_DESC.GW_MAOZI_SHENGDAN = " 格温的圣诞帽"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_MAOZI_SHENGDAN = "格温的圣诞帽"

STRINGS.NAMES.GW_YIFU_SHENGDAN = "圣诞服"
STRINGS.RECIPE_DESC.GW_YIFU_SHENGDAN = " 格温的圣诞服"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_YIFU_SHENGDAN = "格温的圣诞服"

STRINGS.NAMES.GW_REPAIR = "娃娃修补套件"
STRINGS.RECIPE_DESC.GW_REPAIR = "修复你受损的身躯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_REPAIR = "修复你受损的身躯"

STRINGS.NAMES.GW_GIFT = "格温的礼品盒"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GIFT = "里面装有小惊喜~"

STRINGS.NAMES.GW_HUNDENG = "引魂之灯"
STRINGS.RECIPE_DESC.GW_HUNDENG = "我说结束了，那就结束了"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_HUNDENG = "引魂之灯"

STRINGS.NAMES.GW_DUOLUO = "堕落之锋"
STRINGS.RECIPE_DESC.GW_DUOLUO = "遁入黑雾，发动袭击"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_DUOLUO = "堕落之锋"

STRINGS.NAMES.GW_MUHUN = "牧魂人之铲"
STRINGS.RECIPE_DESC.GW_MUHUN = "我前来埋葬你"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_MUHUN = "牧魂人之铲"


STRINGS.NAMES.GW_TASUI = "圣洁踏碎者"
STRINGS.RECIPE_DESC.GW_TASUI = "必须用非凡的手段驱散黑雾"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_TASUI = "圣洁踏碎者"

STRINGS.NAMES.GW_SJMZ = "圣洁魔杖"
STRINGS.RECIPE_DESC.GW_SJMZ = " 远离它的最好办法"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_SJMZ = "圣洁魔杖"

STRINGS.NAMES.GW_MOJING = "格温的墨镜"	
STRINGS.RECIPE_DESC.GW_MOJING = "这会让你变得很coooool"							
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_MOJING = "这会让你变得很coooool"


----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----
----挂件
----雪花
STRINGS.NAMES.GW_GJ_XUEHUA1 = "初级雪花挂件"
STRINGS.RECIPE_DESC.GW_GJ_XUEHUA1 = "象初冬的雪花~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_XUEHUA1 = "象初冬的雪花~\n可以挂在包包上"

STRINGS.NAMES.GW_GJ_XUEHUA2 = "二级雪花挂件"
STRINGS.RECIPE_DESC.GW_GJ_XUEHUA2 = "象寒冬的雪花~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_XUEHUA2 = "象寒冬的雪花~\n可以挂在包包上"

STRINGS.NAMES.GW_GJ_XUEHUA3 = "三级雪花挂件"
STRINGS.RECIPE_DESC.GW_GJ_XUEHUA3 = "象深冬的雪花~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_XUEHUA3 = "象深冬的雪花~\n可以挂在包包上"

----星光
STRINGS.NAMES.GW_GJ_XINGGUANG1 = "初级星光挂件"
STRINGS.RECIPE_DESC.GW_GJ_XINGGUANG1 = "象闪耀的星光~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_XINGGUANG1 = "象闪耀的星光~\n可以挂在包包上"

STRINGS.NAMES.GW_GJ_XINGGUANG2 = "二级星光挂件"
STRINGS.RECIPE_DESC.GW_GJ_XINGGUANG2 = "象璀璨的星光~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_XINGGUANG2 = "象璀璨的星光~\n可以挂在包包上"

STRINGS.NAMES.GW_GJ_XINGGUANG3 = "三级星光挂件"
STRINGS.RECIPE_DESC.GW_GJ_XINGGUANG3 = "象永恒的星光~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_XINGGUANG3 = "象永恒的星光~\n可以挂在包包上"

----哨兵
STRINGS.NAMES.GW_GJ_SHAOBING1 = "初级哨兵挂件"
STRINGS.RECIPE_DESC.GW_GJ_SHAOBING1 = "象巡逻的哨兵~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_SHAOBING1 = "象巡逻的哨兵~\n可以挂在包包上"

STRINGS.NAMES.GW_GJ_SHAOBING2 = "二级哨兵挂件"
STRINGS.RECIPE_DESC.GW_GJ_SHAOBING2 = "象英勇的哨兵~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_SHAOBING2 = "象英勇的哨兵~\n可以挂在包包上"

STRINGS.NAMES.GW_GJ_SHAOBING3 = "三级哨兵挂件"
STRINGS.RECIPE_DESC.GW_GJ_SHAOBING3 = "象无畏的哨兵~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_SHAOBING3 = "象无畏的哨兵~\n可以挂在包包上"

----羽毛
STRINGS.NAMES.GW_GJ_YUMAO1 = "初级羽毛挂件"
STRINGS.RECIPE_DESC.GW_GJ_YUMAO1 = "象轻盈的羽毛~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_YUMAO1 = "象轻盈的羽毛~\n可以挂在包包上"
	
STRINGS.NAMES.GW_GJ_YUMAO2 = "二级羽毛挂件"
STRINGS.RECIPE_DESC.GW_GJ_YUMAO2 = "象舒展的羽毛~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_YUMAO2 = "象舒展的羽毛~\n可以挂在包包上"

STRINGS.NAMES.GW_GJ_YUMAO3 = "三级羽毛挂件"
STRINGS.RECIPE_DESC.GW_GJ_YUMAO3 = "象洁白的羽毛~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_YUMAO3 = "象洁白的羽毛~\n可以挂在包包上"

----智慧
STRINGS.NAMES.GW_GJ_ZHIHUI1 = "初级智慧挂件"
STRINGS.RECIPE_DESC.GW_GJ_ZHIHUI1 = "象思考的智慧~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_ZHIHUI1 = "象思考的智慧~\n可以挂在包包上"

STRINGS.NAMES.GW_GJ_ZHIHUI2 = "二级智慧挂件"
STRINGS.RECIPE_DESC.GW_GJ_ZHIHUI2 = "象启迪的智慧~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_ZHIHUI2 = "象启迪的智慧~\n可以挂在包包上"

STRINGS.NAMES.GW_GJ_ZHIHUI3 = "三级智慧挂件"
STRINGS.RECIPE_DESC.GW_GJ_ZHIHUI3 = "象渊博的智慧~\n可以挂在包包上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GJ_ZHIHUI3 = "象渊博的智慧~\n可以挂在包包上"

----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----
----重构器
STRINGS.NAMES.GW_REFACTOR_1 = "白银重构器"
STRINGS.RECIPE_DESC.GW_REFACTOR_1 = "将你的剪刀升级为白银级~"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_REFACTOR_1 = "重构你的武器~白银级！"

STRINGS.NAMES.GW_REFACTOR_2 = "黄金重构器"
STRINGS.RECIPE_DESC.GW_REFACTOR_2 = "将你的白银剪刀升级为黄金级~"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_REFACTOR_2 = "重构你的武器~黄金级！"

STRINGS.NAMES.GW_REFACTOR_0 = "棱彩碎片\n(可在月台进行激活)"
STRINGS.RECIPE_DESC.GW_REFACTOR_0 = "可在月台进行激活为棱彩重构器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_REFACTOR_0 = "棱彩的碎片~！"
	
STRINGS.NAMES.GW_REFACTOR_3 = "棱彩重构器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_REFACTOR_3 = "重构你的武器~棱彩级！"

----时光沙漏
STRINGS.NAMES.GW_TIME_0 = "时光沙漏"
STRINGS.RECIPE_DESC.GW_TIME_0 = "时间，是一条逆流的河\n将你的等级储存其中"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_TIME_0 = "时间，是一条逆流的河"

----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----
----炼金试剂
STRINGS.NAMES.GW_ALCHEMY_1 = "废品炼金试剂"
STRINGS.RECIPE_DESC.GW_ALCHEMY_1 = "将你的剪刀进行炼成~"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_ALCHEMY_1 = "炼成你的武器~废品啦！"

STRINGS.NAMES.GW_ALCHEMY_2 = "失调炼金试剂"
STRINGS.RECIPE_DESC.GW_ALCHEMY_2 = "将你的剪刀进行炼成~"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_ALCHEMY_2 = "炼成你的武器~失调的！"

STRINGS.NAMES.GW_ALCHEMY_3 = "优质炼金试剂"
STRINGS.RECIPE_DESC.GW_ALCHEMY_3 = "将你的剪刀进行炼成~"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_ALCHEMY_3 = "炼成你的武器~很优质！"
	
STRINGS.NAMES.GW_ALCHEMY_4 = "完美炼金试剂"
STRINGS.RECIPE_DESC.GW_ALCHEMY_4 = "将你的剪刀进行炼成~"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_ALCHEMY_4 = "炼成你的武器~超完美！"

----时光沙漏
STRINGS.NAMES.GW_TIME_0 = "时光沙漏"
STRINGS.RECIPE_DESC.GW_TIME_0 = "时间，是一条逆流的河\n将你的等级储存其中"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_TIME_0 = "时间，是一条逆流的河"

----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----
----格温软糖
STRINGS.NAMES.GW_CANDY = "格温软糖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_CANDY = "酸酸甜甜的软糖~把你的等级提到5级~"

STRINGS.NAMES.GW_LEVEL_UP = "甜蜜方糖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_LEVEL_UP = "甜蜜的方糖，会提升等级"

STRINGS.NAMES.GW_LEVEL_DOWN = "酸涩方糖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_LEVEL_DOWN = "酸涩的方糖，会降低等级"

STRINGS.NAMES.GW_DANGAO = "水果蛋糕"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_DANGAO = "好吃的水果蛋糕~"

----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----
----金锅锅和金铲铲

STRINGS.NAMES.GWEN_GOLDEN_SPATULA = "格温的金铲铲"
STRINGS.RECIPE_DESC.GWEN_GOLDEN_SPATULA = "它必须做点什么..."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GWEN_GOLDEN_SPATULA = "它必须做点什么..."

STRINGS.NAMES.GWEN_GOLDEN_POT = "格温的金锅锅"
STRINGS.RECIPE_DESC.GWEN_GOLDEN_POT = "它必须做点什么..."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GWEN_GOLDEN_POT = "它必须做点什么..."


----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----
----暗影格温
STRINGS.NAMES.GW_SHADOW = "暗影格温"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_SHADOW = "这是暗影格温娃娃"

----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----
----魂灯的幽魂
STRINGS.NAMES.GW_SOUL_BALL = "幽魂"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_SOUL_BALL = "可怜的孤魂野鬼"

----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----
----指针
STRINGS.NAMES.GW_ZHIZHEN = "迷雾指针"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_ZHIZHEN = "去你该去的地方"
STRINGS.RECIPE_DESC.GW_ZHIZHEN = "去你该去的地方..."

----极地号角
STRINGS.NAMES.GWEN_HAOJIAO = "极地号角"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GWEN_HAOJIAO = "弗雷尔卓德这一块"
-- STRINGS.RECIPE_DESC.GWEN_HAOJIAO = "弗雷尔卓德这一块"

----旅行背包
STRINGS.NAMES.GWEN_BACKPACK = "旅行背包"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GWEN_BACKPACK = "格温小姐亲手做的包包"
STRINGS.NAMES.GWEN_BACKPACK_1 = "旅行背包-白银级"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GWEN_BACKPACK_1 = "格温小姐亲手做的包包"
STRINGS.NAMES.GWEN_BACKPACK_2 = "旅行背包-黄金级"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GWEN_BACKPACK_2 = "格温小姐亲手做的包包"
STRINGS.NAMES.GWEN_BACKPACK_3 = "旅行背包-棱彩级"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GWEN_BACKPACK_3 = "格温小姐亲手做的包包"
STRINGS.RECIPE_DESC.GWEN_BACKPACK = "格温小姐亲手做的包包"


----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----[]----
----掘墓相关
STRINGS.NAMES.GW_GRAVE = "可疑的土堆"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GRAVE = "下面到底埋着什么？"

STRINGS.NAMES.GW_GRAVE_CHEST = "被遗忘的坟墓"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_GRAVE_CHEST = "里面肯定有点不得了的玩意"

STRINGS.NAMES.GW_LUOYANG = "洛阳铲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_LUOYANG = "它能指明墓穴的方向"
STRINGS.RECIPE_DESC.GW_LUOYANG = "它能指明墓穴的方向"

STRINGS.NAMES.GW_POCHENG = "破城锤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GW_POCHENG = "它能击碎城墙"
STRINGS.RECIPE_DESC.GW_POCHENG = "击碎城墙"